/**
 * Fixed curriculum metadata + built-in sample content.
 *
 * The learning PATH structure (units/lessons/categories) is fixed here.
 * The CONTENT of each lesson is normally generated by Claude at runtime, but we
 * ship hand-written sample lessons so the app is fully playable offline and
 * before an API key is configured (milestones 2-5 in the plan).
 */

import type { Lesson, LessonMeta, PlacementQuestion } from '@/types';

/** Word categories the user can choose to emphasize during onboarding. */
export const CATEGORIES = [
  { id: 'everyday', label: 'Everyday Conversation', icon: '💬' },
  { id: 'travel', label: 'Travel', icon: '✈️' },
  { id: 'business', label: 'Business', icon: '💼' },
  { id: 'food', label: 'Food & Dining', icon: '🍽️' },
  { id: 'technology', label: 'Technology', icon: '💻' },
  { id: 'academic', label: 'Academic', icon: '🎓' },
] as const;

export type CategoryId = (typeof CATEGORIES)[number]['id'];

/** The ordered path of lessons shown on the home screen. */
export const LESSON_PATH: LessonMeta[] = [
  { id: 'everyday-1', title: 'Greetings & Basics', category: 'everyday', icon: '👋' },
  { id: 'travel-1', title: 'At the Airport', category: 'travel', icon: '✈️' },
  { id: 'food-1', title: 'Ordering Food', category: 'food', icon: '🍽️' },
  { id: 'business-1', title: 'The Office', category: 'business', icon: '💼' },
  { id: 'technology-1', title: 'Devices & Apps', category: 'technology', icon: '💻' },
  { id: 'everyday-2', title: 'Daily Routines', category: 'everyday', icon: '🕘' },
];

/**
 * Built-in sample lessons keyed by lesson id. Used as a fallback when AI
 * generation is unavailable. Each follows the same schema Claude produces.
 */
export const SAMPLE_LESSONS: Record<string, Lesson> = {
  'everyday-1': {
    id: 'everyday-1',
    title: 'Greetings & Basics',
    level: 'A1',
    category: 'everyday',
    xpReward: 20,
    words: [
      { id: 'g-hello', en: 'hello', he: 'שלום (ברכה)', example: 'Hello, how are you today?' },
      { id: 'g-please', en: 'please', he: 'בבקשה', example: 'Can you help me, please?' },
      { id: 'g-thanks', en: 'thank you', he: 'תודה', example: 'Thank you for your help.' },
      { id: 'g-sorry', en: 'sorry', he: 'סליחה', example: 'I am sorry, I am late.' },
    ],
    exercises: [
      { type: 'listen_choose', wordId: 'g-hello', en: 'hello', options: ['שלום (ברכה)', 'להתראות', 'תודה'], answer: 'שלום (ברכה)' },
      { type: 'listen_choose', wordId: 'g-thanks', en: 'thank you', options: ['בבקשה', 'תודה', 'סליחה'], answer: 'תודה' },
      { type: 'multiple_choice', wordId: 'g-please', prompt: 'Which word means "בבקשה"?', options: ['sorry', 'please', 'hello'], answerIndex: 1 },
      { type: 'fill_blank', wordId: 'g-sorry', sentence: 'I am ___, I am late.', options: ['sorry', 'please', 'hello'], answer: 'sorry' },
      { type: 'translate', wordId: 'g-thanks', prompt: 'תרגם: תודה', answer: 'thank you', hints: ['t___ you'] },
    ],
  },
  'travel-1': {
    id: 'travel-1',
    title: 'At the Airport',
    level: 'A2',
    category: 'travel',
    xpReward: 20,
    words: [
      { id: 't-flight', en: 'flight', he: 'טיסה', example: 'My flight leaves at nine.' },
      { id: 't-luggage', en: 'luggage', he: 'מזוודות', example: 'I lost my luggage at the airport.' },
      { id: 't-gate', en: 'gate', he: 'שער (יציאה)', example: 'The gate is closing soon.' },
      { id: 't-boarding', en: 'boarding pass', he: 'כרטיס עלייה למטוס', example: 'Please show your boarding pass.' },
    ],
    exercises: [
      { type: 'listen_choose', wordId: 't-flight', en: 'flight', options: ['טיסה', 'מזוודות', 'שער'], answer: 'טיסה' },
      { type: 'listen_choose', wordId: 't-gate', en: 'gate', options: ['שער (יציאה)', 'טיסה', 'כרטיס'], answer: 'שער (יציאה)' },
      { type: 'multiple_choice', wordId: 't-luggage', prompt: 'Which word means "מזוודות"?', options: ['gate', 'luggage', 'flight'], answerIndex: 1 },
      { type: 'fill_blank', wordId: 't-gate', sentence: 'The ___ is closing soon.', options: ['gate', 'luggage', 'flight'], answer: 'gate' },
      { type: 'translate', wordId: 't-flight', prompt: 'תרגם: טיסה', answer: 'flight', hints: ['f____t'] },
    ],
  },
  'food-1': {
    id: 'food-1',
    title: 'Ordering Food',
    level: 'A2',
    category: 'food',
    xpReward: 20,
    words: [
      { id: 'f-menu', en: 'menu', he: 'תפריט', example: 'Can I see the menu, please?' },
      { id: 'f-order', en: 'to order', he: 'להזמין', example: 'I want to order a coffee.' },
      { id: 'f-bill', en: 'bill', he: 'חשבון', example: 'Can we have the bill, please?' },
      { id: 'f-delicious', en: 'delicious', he: 'טעים', example: 'This soup is delicious.' },
    ],
    exercises: [
      { type: 'listen_choose', wordId: 'f-menu', en: 'menu', options: ['תפריט', 'חשבון', 'טעים'], answer: 'תפריט' },
      { type: 'listen_choose', wordId: 'f-bill', en: 'bill', options: ['חשבון', 'תפריט', 'להזמין'], answer: 'חשבון' },
      { type: 'multiple_choice', wordId: 'f-delicious', prompt: 'Which word means "טעים"?', options: ['bill', 'delicious', 'menu'], answerIndex: 1 },
      { type: 'fill_blank', wordId: 'f-order', sentence: 'I want to ___ a coffee.', options: ['order', 'menu', 'bill'], answer: 'order' },
      { type: 'translate', wordId: 'f-menu', prompt: 'תרגם: תפריט', answer: 'menu', hints: ['m___'] },
    ],
  },
  'business-1': {
    id: 'business-1',
    title: 'The Office',
    level: 'B1',
    category: 'business',
    xpReward: 20,
    words: [
      { id: 'b-meeting', en: 'meeting', he: 'פגישה', example: 'We have a meeting at ten.' },
      { id: 'b-deadline', en: 'deadline', he: 'מועד אחרון', example: 'The deadline is on Friday.' },
      { id: 'b-report', en: 'report', he: 'דו"ח', example: 'Please send me the report.' },
      { id: 'b-colleague', en: 'colleague', he: 'עמית לעבודה', example: 'She is my colleague.' },
    ],
    exercises: [
      { type: 'listen_choose', wordId: 'b-meeting', en: 'meeting', options: ['פגישה', 'דו"ח', 'מועד אחרון'], answer: 'פגישה' },
      { type: 'listen_choose', wordId: 'b-report', en: 'report', options: ['דו"ח', 'פגישה', 'עמית'], answer: 'דו"ח' },
      { type: 'multiple_choice', wordId: 'b-deadline', prompt: 'Which word means "מועד אחרון"?', options: ['meeting', 'deadline', 'report'], answerIndex: 1 },
      { type: 'fill_blank', wordId: 'b-meeting', sentence: 'We have a ___ at ten.', options: ['meeting', 'report', 'deadline'], answer: 'meeting' },
      { type: 'translate', wordId: 'b-report', prompt: 'תרגם: דו"ח', answer: 'report', hints: ['r____t'] },
    ],
  },
  'technology-1': {
    id: 'technology-1',
    title: 'Devices & Apps',
    level: 'A2',
    category: 'technology',
    xpReward: 20,
    words: [
      { id: 'tech-screen', en: 'screen', he: 'מסך', example: 'The screen is too bright.' },
      { id: 'tech-battery', en: 'battery', he: 'סוללה', example: 'My battery is low.' },
      { id: 'tech-download', en: 'to download', he: 'להוריד (קובץ)', example: 'I need to download the app.' },
      { id: 'tech-password', en: 'password', he: 'סיסמה', example: 'I forgot my password.' },
    ],
    exercises: [
      { type: 'listen_choose', wordId: 'tech-screen', en: 'screen', options: ['מסך', 'סוללה', 'סיסמה'], answer: 'מסך' },
      { type: 'listen_choose', wordId: 'tech-battery', en: 'battery', options: ['סוללה', 'מסך', 'להוריד'], answer: 'סוללה' },
      { type: 'multiple_choice', wordId: 'tech-password', prompt: 'Which word means "סיסמה"?', options: ['screen', 'password', 'battery'], answerIndex: 1 },
      { type: 'fill_blank', wordId: 'tech-battery', sentence: 'My ___ is low.', options: ['battery', 'screen', 'password'], answer: 'battery' },
      { type: 'translate', wordId: 'tech-screen', prompt: 'תרגם: מסך', answer: 'screen', hints: ['s____n'] },
    ],
  },
  'everyday-2': {
    id: 'everyday-2',
    title: 'Daily Routines',
    level: 'A1',
    category: 'everyday',
    xpReward: 20,
    words: [
      { id: 'd-wake', en: 'to wake up', he: 'להתעורר', example: 'I wake up at seven.' },
      { id: 'd-breakfast', en: 'breakfast', he: 'ארוחת בוקר', example: 'I eat breakfast every morning.' },
      { id: 'd-work', en: 'to work', he: 'לעבוד', example: 'I work from home.' },
      { id: 'd-sleep', en: 'to sleep', he: 'לישון', example: 'I go to sleep at eleven.' },
    ],
    exercises: [
      { type: 'listen_choose', wordId: 'd-wake', en: 'wake up', options: ['להתעורר', 'לישון', 'לעבוד'], answer: 'להתעורר' },
      { type: 'listen_choose', wordId: 'd-breakfast', en: 'breakfast', options: ['ארוחת בוקר', 'לעבוד', 'לישון'], answer: 'ארוחת בוקר' },
      { type: 'multiple_choice', wordId: 'd-work', prompt: 'Which word means "לעבוד"?', options: ['sleep', 'work', 'breakfast'], answerIndex: 1 },
      { type: 'fill_blank', wordId: 'd-sleep', sentence: 'I go to ___ at eleven.', options: ['sleep', 'work', 'breakfast'], answer: 'sleep' },
      { type: 'translate', wordId: 'd-breakfast', prompt: 'תרגם: ארוחת בוקר', answer: 'breakfast', hints: ['b_______t'] },
    ],
  },
};

/** Fallback placement quiz used when AI generation is unavailable. */
export const SAMPLE_PLACEMENT_QUIZ: PlacementQuestion[] = [
  { level: 'A1', prompt: 'Choose the correct greeting: "___, how are you?"', options: ['Hello', 'Table', 'Green'], answerIndex: 0 },
  { level: 'A1', prompt: 'What is the plural of "cat"?', options: ['cates', 'cats', 'cat'], answerIndex: 1 },
  { level: 'A2', prompt: 'Complete: "She ___ to school every day."', options: ['go', 'goes', 'going'], answerIndex: 1 },
  { level: 'A2', prompt: 'Choose the past tense of "eat".', options: ['eated', 'ate', 'eaten'], answerIndex: 1 },
  { level: 'B1', prompt: 'Complete: "If it rains, we ___ stay home."', options: ['will', 'would have', 'were'], answerIndex: 0 },
  { level: 'B1', prompt: 'Which sentence is correct?', options: ['I have been here since 2020.', 'I am here since 2020.', 'I here since 2020.'], answerIndex: 0 },
  { level: 'B2', prompt: 'Choose the best word: "The report was ___ detailed."', options: ['remarkably', 'remark', 'remarking'], answerIndex: 0 },
  { level: 'C1', prompt: 'Complete: "Had I known, I ___ acted differently."', options: ['will have', 'would have', 'have'], answerIndex: 1 },
];
